name: png_colorizer
description: "Swap PNG colors."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  file_picker: ^5.0.1
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_svg: ^2.0.17
  image: ^4.5.2
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
